language: node_js
node_js:
  - node
services:
  - mongod
before_install:
  - npm install -g mocha
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - npm install
  - bower install
script:
  - npm run build
  - npm test